<template>
  <div style="max-width:1100px;margin:0 auto">
    <!-- Stats -->
    <el-row :gutter="12" style="margin-bottom:12px">
      <el-col :span="3"><el-card shadow="never"><div style="text-align:center;padding:4px"><div style="font-size:20px;font-weight:700;color:#409eff">{{ stats.total }}</div><div style="font-size:11px;color:#909399">总任务</div></div></el-card></el-col>
      <el-col :span="4"><el-card shadow="never"><div style="text-align:center;padding:4px"><div style="font-size:20px;font-weight:700;color:#e6a23c">{{ stats.pending }}</div><div style="font-size:11px;color:#909399">待回访</div></div></el-card></el-col>
      <el-col :span="4"><el-card shadow="never"><div style="text-align:center;padding:4px"><div style="font-size:20px;font-weight:700;color:#67c23a">{{ stats.completed }}</div><div style="font-size:11px;color:#909399">已完成</div></div></el-card></el-col>
      <el-col :span="4"><el-card shadow="never"><div style="text-align:center;padding:4px"><div style="font-size:20px;font-weight:700;color:#f56c6c">{{ stats.overdue }}</div><div style="font-size:11px;color:#909399">已逾期</div></div></el-card></el-col>
      <el-col :span="4"><el-card shadow="never"><div style="text-align:center;padding:4px"><div style="font-size:20px;font-weight:700;color:#67c23a">{{ stats.completed > 0 ? convStats.rate+'%' : '--' }}</div><div style="font-size:11px;color:#909399">完成率</div></div></el-card></el-col>
      <el-col :span="5"><el-card shadow="never"><div style="text-align:center;padding:4px"><div style="font-size:20px;font-weight:700;color:#409eff">{{ convStats.rebooked }}/{{ convStats.completed }}</div><div style="font-size:11px;color:#909399">转化(复购/回访)</div></div></el-card></el-col>
    </el-row>

    <!-- Toolbar -->
    <el-card shadow="never" style="margin-bottom:14px">
      <div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">
        <el-radio-group v-model="typeTab" @change="loadTasks" size="small">
          <el-radio-button value="">全部</el-radio-button>
          <el-radio-button value="post_treatment">治疗后</el-radio-button>
          <el-radio-button value="birthday">生日关怀</el-radio-button>
          <el-radio-button value="dormant">沉睡唤醒</el-radio-button>
          <el-radio-button value="custom">自定义</el-radio-button>
        </el-radio-group>
        <el-select v-model="statusFilter" placeholder="状态" clearable style="width:90px" size="small" @change="loadTasks">
          <el-option label="待回访" value="pending"/><el-option label="已完成" value="completed"/>
        </el-select>
        <el-select v-model="assignedFilter" placeholder="负责人" clearable style="width:110px" size="small" @change="loadTasks">
          <el-option v-for="s in staffList" :key="s.id" :label="s.real_name" :value="s.id"/>
        </el-select>
        <div style="flex:1"/>
        <el-button size="small" @click="autoGenerateDormant">生成沉睡回访</el-button>
        <el-button size="small" @click="openCreate">+ 新建回访</el-button>
        <el-button size="small" text @click="exportCSV">导出</el-button>
      </div>
    </el-card>

    <!-- View Tabs -->
    <el-card shadow="never">
      <el-tabs v-model="viewTab">
        <!-- ====== List View ====== -->
        <el-tab-pane label="📋 列表视图" name="list">
          <el-table :data="tasks" v-loading="loading" stripe size="small" max-height="500">
            <el-table-column label="客户" min-width="100"><template #default="{row}"><el-button text size="small" @click="openHistory(row)" style="padding:0">{{ row.customer?.name||'未知' }}</el-button></template></el-table-column>
            <el-table-column label="电话" width="100"><template #default="{row}">{{ row.customer?.phone||'-' }}</template></el-table-column>
            <el-table-column label="类型" width="80"><template #default="{row}">{{ typeLabel(row.type) }}{{ row.type==='post_treatment' && row.due_date ? ' D'+(calcDay(row.due_date)||'') : '' }}</template></el-table-column>
            <el-table-column label="截止" width="85"><template #default="{row}"><span :style="row.status==='pending'&&row.due_date&&new Date(row.due_date).getTime()<Date.now()?{color:'#f56c6c',fontWeight:'700'}:{}">{{ row.due_date||'--' }}</span></template></el-table-column>
            <el-table-column label="状态" width="65"><template #default="{row}"><el-tag :type="row.status==='completed'?'success':'warning'" size="small">{{ row.status==='completed'?'已回访':'待回访' }}</el-tag></template></el-table-column>
            <el-table-column label="负责人" width="70"><template #default="{row}">{{ userName(row.assigned_to)||'--' }}</template></el-table-column>
            <el-table-column label="话术" width="40" align="center">
              <template #default="{row}">
                <el-tooltip :content="scriptHint(row)" placement="left" :show-after="200">
                  <el-icon><InfoFilled /></el-icon>
                </el-tooltip>
              </template>
            </el-table-column>
            <el-table-column label="备注" min-width="100" prop="note"/>
            <el-table-column label="操作" width="100" fixed="right">
              <template #default="{row}">
                <el-button v-if="row.status==='pending'" size="small" type="success" @click="openComplete(row)">完成</el-button>
                <el-button v-else-if="row.result_status==='rebooked'" size="small" text type="primary" style="color:#67c23a">已复购</el-button>
                <span v-else style="color:#c0c4cc;font-size:12px">--</span>
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>

        <!-- ====== Calendar View ====== -->
        <el-tab-pane label="📅 日历视图" name="calendar">
          <el-calendar v-model="calendarDate">
            <template #dateCell="{date,data}">
              <div style="position:relative;min-height:50px">
                <div style="font-size:12px">{{ data.day.split('-').slice(2)[0] }}</div>
                <div v-for="t in tasksByDate(data.day)" :key="t.id" style="font-size:10px;padding:1px 2px;margin:1px 0;border-radius:2px;cursor:pointer;overflow:hidden;white-space:nowrap;text-overflow:ellipsis"
                  :style="{background:t.status==='completed'?'#e1f3d8':t.status==='pending'&&t.due_date&&new Date(t.due_date).getTime()<Date.now()?'#fde2e2':'#d9ecff',color:t.status==='completed'?'#67c23a':'#409eff'}"
                  @click="openComplete(t)">
                  {{ t.customer?.name?.slice(0,3)||'?' }} {{ typeLabel(t.type).slice(0,2) }}
                </div>
              </div>
            </template>
          </el-calendar>
        </el-tab-pane>

        <!-- ====== Stats View ====== -->
        <el-tab-pane label="📊 转化统计" name="stats">
          <div style="margin-bottom:12px">
            <el-table :data="statsBreakdown" stripe border size="small">
              <el-table-column label="回访类型" min-width="100"><template #default="{row}">{{ typeLabel(row.type) }}</template></el-table-column>
              <el-table-column label="总任务" prop="total" width="60" align="center"/>
              <el-table-column label="已完成" prop="completed" width="60" align="center"/>
              <el-table-column label="完成率" width="60" align="center"><template #default="{row}"><el-tag :type="row.rate>=80?'success':row.rate>=50?'warning':'danger'" size="small">{{ row.rate }}%</el-tag></template></el-table-column>
              <el-table-column label="促成复购" prop="rebooked" width="70" align="center"/>
              <el-table-column label="转化率" width="60" align="center"><template #default="{row}"><el-tag :type="row.conv_rate>=30?'success':row.conv_rate>=10?'warning':'info'" size="small">{{ row.conv_rate }}%</el-tag></template></el-table-column>
            </el-table>
          </div>
          <div v-for="r in statsBreakdown" :key="r.type" style="margin-bottom:16px">
            <div style="font-weight:600;margin-bottom:6px">{{ typeLabel(r.type) }}</div>
            <div style="background:#f5f7fa;padding:10px;border-radius:6px;font-size:13px;color:#606266;line-height:1.7">
              {{ scriptHintByType(r.type) }}
            </div>
          </div>
        </el-tab-pane>
      </el-tabs>
    </el-card>

    <!-- ====== Create Dialog ====== -->
    <el-dialog v-model="createVisible" title="新建回访任务" width="480px">
      <el-form label-width="80px" size="small">
        <el-form-item label="客户" required>
          <el-select v-model="createForm.customer_id" filterable remote :remote-method="searchCust" :loading="custLoading" placeholder="搜索客户" style="width:100%">
            <el-option v-for="c in custOptions" :key="c.id" :label="c.name+'('+(c.phone||'')+')'" :value="c.id"/>
          </el-select>
        </el-form-item>
        <el-form-item label="类型" required>
          <el-select v-model="createForm.type" style="width:100%">
            <el-option v-for="(l,k) in typeL" :key="k" :label="l" :value="k"/>
          </el-select>
        </el-form-item>
        <el-form-item label="截止日期" required>
          <el-date-picker v-model="createForm.due_date" type="date" value-format="YYYY-MM-DD" style="width:100%"/>
        </el-form-item>
        <el-form-item label="负责人">
          <el-select v-model="createForm.assigned_to" placeholder="选择员工" clearable style="width:100%">
            <el-option v-for="s in staffList" :key="s.id" :label="s.real_name" :value="s.id"/>
          </el-select>
        </el-form-item>
        <el-form-item label="备注">
          <el-input v-model="createForm.note" type="textarea" :rows="2"/>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="createVisible=false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="submitCreate">创建</el-button>
      </template>
    </el-dialog>

    <!-- ====== Complete Dialog ====== -->
    <el-dialog v-model="completeVisible" title="完成回访" width="500px">
      <div v-if="completing" style="margin-bottom:12px">
        <div style="font-size:13px;color:#909399;margin-bottom:8px">
          {{ completing.customer?.name }} — {{ typeLabel(completing.type) }}
          <span v-if="completing.due_date"> — {{ completing.due_date }}</span>
        </div>
        <!-- Script hint -->
        <div style="background:#f0f5ff;padding:10px;border-radius:6px;margin-bottom:12px;font-size:13px;color:#303133;line-height:1.7">
          <div style="font-weight:600;color:#409eff;margin-bottom:4px">💡 建议话术</div>
          {{ scriptHint(completing) }}
        </div>
      </div>
      <el-form label-width="80px" size="small">
        <el-form-item label="回访结果">
          <el-select v-model="completeForm.result_status" placeholder="请选择结果" style="width:100%">
            <el-option label="✅ 恢复良好，无异常" value="satisfied"/>
            <el-option label="🔄 已预约复购/复诊" value="rebooked"/>
            <el-option label="⚠️ 有不适，已建议复诊" value="discomfort"/>
            <el-option label="📞 未接通" value="no_answer"/>
            <el-option label="😠 投诉/纠纷" value="complaint"/>
            <el-option label="📝 其他" value="other"/>
          </el-select>
        </el-form-item>
        <el-form-item label="沟通记录">
          <el-input v-model="completeForm.result" type="textarea" :rows="4" placeholder="记录回访沟通内容、客户反馈等"/>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="completeVisible=false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="submitComplete">确认完成</el-button>
      </template>
    </el-dialog>

    <!-- ====== History Dialog ====== -->
    <el-dialog :model-value="histDialog" :title="'回访记录 — '+ (histCustomer||'')" width="600px" @update:model-value="histDialog=$event">
      <el-table :data="histTasks" stripe border size="small">
        <el-table-column label="类型" width="80"><template #default="{row}">{{ typeLabel(row.type) }}</template></el-table-column>
        <el-table-column label="截止日期" width="80" prop="due_date"/>
        <el-table-column label="状态" width="60"><template #default="{row}"><el-tag :type="row.status==='completed'?'success':'warning'" size="small">{{ row.status==='completed'?'已回访':'待回访' }}</el-tag></template></el-table-column>
        <el-table-column label="结果" width="60"><template #default="{row}">{{ resultLabel(row.result_status) }}</template></el-table-column>
        <el-table-column label="沟通内容" min-width="100" prop="result"/>
      </el-table>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { InfoFilled } from '@element-plus/icons-vue'
import api from '../../api'

const loading = ref(false)
const tasks = ref<any[]>([])
const statusFilter = ref('')
const typeTab = ref('')
const assignedFilter = ref('')
const viewTab = ref('list')
const calendarDate = ref(new Date())

// Type labels
const typeL: Record<string, string> = {
  post_treatment: '治疗后回访', dormant: '沉睡唤醒',
  birthday: '生日关怀', custom: '自定义'
}
function typeLabel(s: string) { return typeL[s] || s || '未知' }

// Result labels
const resultL: Record<string, string> = {
  satisfied: '恢复良好', rebooked: '已预约复购',
  discomfort: '有不适', no_answer: '未接通',
  complaint: '投诉', other: '其他'
}
function resultLabel(s: string) { return resultL[s] || s || '--' }

// Script hints
const SCRIPT_HINTS: Record<string, Record<string, string>> = {
  post_treatment: {
    title: '治疗后回访话术',
    d1: '您好，我是东芳美诊所的客服。昨天做完治疗后，您感觉怎么样？有没有出现红肿、疼痛等不适？请您注意保持治疗部位清洁，避免暴晒和剧烈运动。',
    d3: '您好，打扰您了。三天前做完治疗，现在恢复得怎么样了？如果有任何疑问或不适，欢迎随时联系我们。',
    d7: '您好，一周过去了，顺便关心一下您治疗后的恢复情况。初步效果您觉得满意吗？建议您近期可以来复诊一下。',
    d30: '您好，一个月过去了，想了解一下您对治疗效果的满意度。您的反馈对我们非常重要，如果有任何问题可以随时到店复诊。',
    default: '您好，我是东芳美诊所的客服，想了解一下您治疗后的恢复情况，有什么需要帮助的吗？'
  },
  dormant: { title: '沉睡唤醒话术', text: '您好，我是东芳美诊所的客服。好久不见，最近我们有一些老客户回馈活动，想邀请您来店体验一下。您方便的时候可以预约哦。' },
  birthday: { title: '生日关怀话术', text: '您好，我是东芳美诊所的客服。今天是您的生日，祝您生日快乐！我们为您准备了一份生日专属礼物，欢迎您来店领取。祝您越来越年轻美丽！' },
  custom: { title: '自定义回访', text: '根据实际情况进行回访沟通。' }
}
function calcDay(due: string): number | null {
  if (!due) return null
  // Try to calculate D-day by looking at the day relative to something
  // For display, just show the last 2 digits
  return null
}
function scriptHintByType(type: string): string {
  const h = SCRIPT_HINTS[type]
  if (!h) return ''
  return h.title + '：' + (h.text || h.default || '')
}
function scriptHint(row: any): string {
  if (!row) return ''
  const h = SCRIPT_HINTS[row.type]
  if (!h) return '无预设话术'
  if (row.type === 'post_treatment' && row.note) {
    // Try to detect D1/D3/D7/D30 from the note
    if (row.note.includes('第1天') || row.note.includes('D1')) return h.d1
    if (row.note.includes('第3天') || row.note.includes('D3')) return h.d3
    if (row.note.includes('第7天') || row.note.includes('D7')) return h.d7
    if (row.note.includes('第30天') || row.note.includes('D30')) return h.d30
  }
  return h.text || h.default || h.title || ''
}

// Stats computed from tasks
const stats = computed(() => {
  const a = tasks.value
  const now = Date.now()
  const pending = a.filter(x => x.status === 'pending').length
  const completed = a.filter(x => x.status === 'completed').length
  const overdue = a.filter(x => x.status === 'pending' && x.due_date && new Date(x.due_date).getTime() < now).length
  const rate = a.length > 0 ? Math.round(completed / a.length * 100) : 0
  const rebooked = a.filter(x => x.result_status === 'rebooked').length
  return { total: a.length, pending, completed, overdue, rate, rebooked }
})

// Breakdown stats
const statsBreakdown = computed(() => {
  const map: Record<string, any> = {}
  tasks.value.forEach((x: any) => {
    const t = x.type || 'undefined'
    if (!map[t]) map[t] = { type: t, total: 0, completed: 0, rebooked: 0, rate: 0, conv_rate: 0 }
    map[t].total++
    if (x.status === 'completed') map[t].completed++
    if (x.result_status === 'rebooked') map[t].rebooked++
  })
  return Object.values(map).map(r => ({
    ...r,
    rate: r.total > 0 ? Math.round(r.completed / r.total * 100) : 0,
    conv_rate: r.completed > 0 ? Math.round(r.rebooked / r.completed * 100) : 0
  }))
})

// Conversion stats from API
const convStats = reactive({ total: 0, completed: 0, rebooked: 0, rate: '0%' })
async function loadConvStats() {
  try {
    const r = await api.get('/followup/tasks/stats')
    const d = r.data
    if (d?.overall) {
      convStats.total = d.overall.total || 0
      convStats.completed = d.overall.completed || 0
      convStats.rebooked = d.overall.rebooked || 0
      convStats.rate = (d.overall.rate || 0).toFixed(1) + '%'
    }
  } catch { }
}

// Calendar helper
function tasksByDate(date: string) {
  return tasks.value.filter(t => t.due_date === date)
}

// Staff list
const staffList = ref<any[]>([])
async function loadStaff() {
  try {
    const r = await api.get('/users')
    staffList.value = Array.isArray(r.data) ? r.data.filter((u: any) => u.status === 'active') : []
  } catch { staffList.value = [] }
}
function userName(id: number | null): string {
  if (!id) return ''
  const s = staffList.value.find(u => u.id === id)
  return s?.real_name || ''
}

// Load tasks
async function loadTasks() {
  loading.value = true
  try {
    const params: any = {}
    if (statusFilter.value) params.status = statusFilter.value
    if (typeTab.value) params.type = typeTab.value
    if (assignedFilter.value) params.assigned_to = assignedFilter.value
    const r = await api.get('/followup/tasks', { params })
    tasks.value = Array.isArray(r.data) ? r.data : []
  } catch { tasks.value = [] }
  finally { loading.value = false }
}

// Create dialog
const createVisible = ref(false)
const saving = ref(false)
const custOptions = ref<any[]>([])
const custLoading = ref(false)
const createForm = ref({ customer_id: null, type: 'custom', due_date: '', assigned_to: null, note: '' })

async function searchCust(q: string) {
  if (!q) { custOptions.value = []; return }
  custLoading.value = true
  try {
    const r = await api.get('/customers', { params: { q, page_size: 20 } })
    custOptions.value = Array.isArray(r.data) ? r.data : (r.data?.data || [])
  } catch { custOptions.value = [] }
  finally { custLoading.value = false }
}

function openCreate() {
  createForm.value = { customer_id: null, type: 'custom', due_date: new Date().toISOString().slice(0, 10), assigned_to: null, note: '' }
  createVisible.value = true
}

async function submitCreate() {
  if (!createForm.value.customer_id) { ElMessage.warning('请选择客户'); return }
  if (!createForm.value.due_date) { ElMessage.warning('请选择截止日期'); return }
  saving.value = true
  try {
    await api.post('/followup/tasks', createForm.value)
    ElMessage.success('创建成功')
    createVisible.value = false
    await loadTasks()
  } catch (e: any) { ElMessage.error(e?.response?.data?.error || '创建失败') }
  finally { saving.value = false }
}

// Complete dialog
const completeVisible = ref(false)
const completing = ref<any>(null)
const completeForm = ref({ result: '', result_status: '' })

function openComplete(row: any) {
  completing.value = row
  completeForm.value = { result: '', result_status: '' }
  completeVisible.value = true
}

async function submitComplete() {
  if (!completing.value?.id) return
  saving.value = true
  try {
    await api.put('/followup/tasks/' + completing.value.id + '/complete', completeForm.value)
    ElMessage.success('已完成')
    completeVisible.value = false
    completing.value = null
    await loadTasks()
    await loadConvStats()
  } catch (e: any) { ElMessage.error(e?.response?.data?.error || '操作失败') }
  finally { saving.value = false }
}

// Auto-generate
async function autoGenerateDormant() {
  try {
    const r = await api.post('/followup/tasks/auto-generate')
    ElMessage.success(r.data?.message || '已生成')
    await loadTasks()
  } catch (e: any) { ElMessage.error(e?.response?.data?.error || '生成失败') }
}

async function autoGeneratePostTreatment() {
  try {
    const r = await api.post('/followup/tasks/auto-generate-post-treatment', { customer_id: 0, treat_date: '' })
    ElMessage.success(r.data?.message || '已生成')
    await loadTasks()
  } catch { }
}

// Export CSV
function exportCSV() {
  const a = tasks.value; if (!a.length) return
  const sep = ',', nl = '\n'
  const h = '客户' + sep + '电话' + sep + '类型' + sep + '截止日期' + sep + '状态' + sep + '负责人' + sep + '回访结果' + sep + '沟通记录' + sep + '备注'
  const r = a.map(function (x: any) {
    return [x.customer?.name || '', x.customer?.phone || '', typeLabel(x.type), x.due_date || '',
      x.status === 'completed' ? '已回访' : '待回访', userName(x.assigned_to), resultLabel(x.result_status),
      x.result || '', x.note || ''].join(sep)
  }).join(nl)
  const blob = new Blob(['\ufeff' + h + nl + r], { type: 'text/csv;charset=utf-8' })
  const el = document.createElement('a')
  el.href = URL.createObjectURL(blob)
  el.download = '回访任务_' + new Date().toISOString().slice(0, 10) + '.csv'
  el.click()
  URL.revokeObjectURL(el.href)
}

// History dialog
const histDialog = ref(false)
const histCustomer = ref('')
const histTasks = ref<any[]>([])
function openHistory(row: any) {
  histCustomer.value = row.customer?.name || '未知'
  const name = row.customer?.name || ''
  histTasks.value = tasks.value.filter((x: any) => (x.customer?.name || '') === name)
  histDialog.value = true
}

onMounted(() => { loadTasks(); loadStaff(); loadConvStats() })
</script>
